/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118905-gcbbc927a67-20250324"
#endif /* AVUTIL_FFVERSION_H */
